// src/sections/MainSection/index.jsx
import { HeadingItem } from '../../components/HeadingItem'
import { BlockItem } from '../../components/BlockItem'
import { TagItem } from '../../components/TagItem'

export function MainSection({
  summary,
  works,
  education,
  certificates,
  skills,
  languages,
}) {
  return (
    <section className='section'>
      <div className='container'>
        <div className='columns'>
          <div className='column is-three-fifths'>
            <div className='summary'>
              <HeadingItem title='DESCRIPCION'></HeadingItem>
              <div className='wrapper'>
                <p style={{ whiteSpace: 'pre-wrap' }}>{summary}</p>
              </div>
            </div>
            <div className='experience'>
              <HeadingItem title='EXPERIENCIA'></HeadingItem>
              {works.map((work, index) => (
                <BlockItem
                  key={index}
                  title={work.name}
                  subtitle={work.position}
                  startDate={work.startDate}
                  endDate={work.endDate}
                  description={work.summary}
                />
              ))}
            </div>

            <div className='education'>
              <HeadingItem title='EDUCACION'></HeadingItem>
              {education.map((degree, index) => (
                <BlockItem
                  key={index}
                  title={degree.institution}
                  subtitle={degree.studyType}
                  startDate={degree.startDate}
                />
              ))}
            </div>
          </div>
          <div className='column'>
            <div className='education'>
              <HeadingItem title='CERTIFICADOS'></HeadingItem>
              {certificates.map((certificate, index) => (
                <BlockItem
                  key={index}
                  title={certificate.issuer}
                  subtitle={certificate.name}
                  startDate={certificate.startDate}
                />
              ))}
            </div>
            <div className='skills'>
              <HeadingItem title='HABILIDADES'></HeadingItem>
              <div className='wrapper'>
                <div className='item is-flex is-flex-wrap-wrap is-flex-direction-row is-align-items-center'>
                  {skills.map((skill, index) => (
                    <TagItem
                      key={index}
                      text={skill.name}
                    ></TagItem>
                  ))}
                </div>
              </div>
            </div>

            <div className='languages'>
              <HeadingItem title='IDIOMAS'></HeadingItem>
              <div className='wrapper'>
                <div className='item'>
                  {languages.map((language, index) => (
                    <div key={index}>
                      {language.language}
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// components/MainSection/MainSection.vue
<template>
  <section class="section">
    <div class="container">
      <div class="columns">
        <div class="column is-three-fifths">
          <div class="summary">
            <TitleItem title="DESCRIPCION"></TitleItem>
            <div class="wrapper">
              <p style="white-space: pre-wrap">{{ summary }}</p>
            </div>
          </div>
          <div class="experience">
            <TitleItem title="EXPERIENCIA"></TitleItem>
            <BlockItem v-for="work in works" :key="work.name" :title="work.name" :subtitle="work.position"
              :start-date="work.startDate" :end-date="work.endDate" :description="work.summary"></BlockItem>
          </div>

          <div class="education">
            <TitleItem title="EDUCACION"></TitleItem>
            <BlockItem v-for="degree in education" :key="degree.institution" :title="degree.institution"
              :subtitle="degree.studyType" :start-date="degree.startDate"></BlockItem>
          </div>
        </div>
        <div class="column">
          <div class="education">
            <TitleItem title="CERTIFICADOS"></TitleItem>
            <BlockItem v-for="certificate in certificates" :key="certificate.name" :title="certificate.issuer"
              :subtitle="certificate.name" :start-date="certificate.startDate"></BlockItem>
          </div>
          <div class="skills">
            <TitleItem title="HABILIDADES"></TitleItem>
            <div class="wrapper">
              <div class="item is-flex is-flex-wrap-wrap is-flex-direction-row is-align-items-center	">
                <TagItem v-for="skill in skills" :key="skill.name" :text="skill.name" class="m-1"></TagItem>
              </div>
            </div>
          </div>

          <div class="languages">
            <TitleItem title="IDIOMAS">
            </TitleItem>
            <div class="wrapper">
              <div class="item">
                <div v-for="language in languages" :key="language.language">
                  {{ language.language }}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import BlockItem from './BlockItem/BlockItem'
import TitleItem from './TitleItem/TitleItem'
import TagItem from './TagItem/TagItem'

export default {
  components: {
    BlockItem,
    TitleItem,
    TagItem
  },
  props: {
    summary: {
      type: String,
      required: true
    },
    works: {
      type: Array,
      required: true
    },
    education: {
      type: Array,
      required: true
    },
    certificates: {
      type: Array,
      required: false,
      default: () => []
    },
    projects: {
      type: Array,
      required: false,
      default: () => []
    },
    skills: {
      type: Array,
      required: true,
      default: () => []
    },
    languages: {
      type: Array,
      required: true
    }
  }
}
</script>
