// components/MainSection/BlockItem/BlockItem.vue
<template>
  <div class="item">
    <div class="is-size-5">
      <b>
        {{ title }},
      </b>
      <span class="has-text-weight-semi-bold">
        <i>{{ subtitle }}</i>
      </span>
    </div>
    <TagItem :text="initDate + finishDate">
    </TagItem>
    <div>
      {{ description }}
    </div>
  </div>
</template>

<script>
import { format } from 'date-fns'
import TagItem from '../TagItem/TagItem'

const DATE_FORMAT = 'dd-MM-yyyy'

export default {
  name: 'BlockItem',
  components: {
    TagItem
  },
  props: {
    title: {
      type: String,
      required: true
    },
    subtitle: {
      type: String,
      required: true
    },
    startDate: {
      type: String,
      required: true
    },
    endDate: {
      type: String,
      required: false,
      default: () => ''
    },
    description: {
      type: String,
      required: false,
      default: ''
    }
  },
  data() {
    return {
      initDate: format(new Date(this.startDate), DATE_FORMAT),
      finishDate: this.endDate ? ` - ${format(new Date(this.endDate), DATE_FORMAT)}` : ''
    }
  }
}
</script>

// src/components/BlockItem/index.jsx
import { TagItem } from '../TagItem';

export function BlockItem({
  title,
  subtitle,
  description,
  startDate,
  endDate,
}) {
  const COMPLETE_DATE_STRING = `${startDate} / ${endDate}`
  const TAG_TEXT = endDate ? COMPLETE_DATE_STRING : startDate;

  return (
    <div className='item'>
      <div className='is-size-5'>
        <b>{title}</b>
        <b className='ml-1'>-</b>
        <span className='has-text-weight-semi-bold ml-1'>
          <i>{subtitle}</i>
        </span>
      </div>
      <TagItem text={TAG_TEXT}></TagItem>
      <div className='py-2'>{description}</div>
    </div>
  );
}
